server:
  port: 9005
nacos:
  host: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cem.mysql.com:3306/CEM_DEV_UAA?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.host}:${nacos.port}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wangsheng.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true
