server:
  port: 5000

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9005/.well-known/jwks.json
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: example-service
        uri: lb://example-service
        predicates:
        - Path=/example-service/**
        filters:
        - RewritePath=/example-service(?<segment>/?.*), $\{segment}
      - id: example-client
        uri: lb://example-client
        predicates:
        - Path=/example-client/**
        filters:
        - RewritePath=/example-client(?<segment>/?.*), $\{segment}
      - id: user-center
        uri: lb://user-center
        predicates:
        - Path=/user-center/**
        filters:
        - RewritePath=/user-center(?<segment>/?.*), $\{segment}
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth-service/**
        filters:
        - RewritePath=/auth-service(?<segment>/?.*), $\{segment}
